version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 435506672220.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t credit-risk-ai .
      - docker tag credit-risk-ai:latest 435506672220.dkr.ecr.ap-south-1.amazonaws.com/credit-risk-ai:latest
  post_build:
    commands:
      - docker push 435506672220.dkr.ecr.ap-south-1.amazonaws.com/credit-risk-ai:latest