cat > buildspec.yml << 'EOF'
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 435506672220.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t credit-risk-ai .
      - docker tag credit-risk-ai:latest 435506672220.dkr.ecr.ap-south-1.amazonaws.com/credit-risk-ai:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 435506672220.dkr.ecr.ap-south-1.amazonaws.com/credit-risk-ai:latest
      - echo Build complete!
EOF